name: Release Self-Hosted Backend

on:
  workflow_call:
    outputs:
      backend_x64_digest:
        description: "x64 image digest"
        value: ${{ fromJson(jobs.read.outputs.result).digest.backend-x64 }}
      backend_arm64_digest:
        description: "arm64 image digest"
        value: ${{ fromJson(jobs.read.outputs.result).digest.backend-arm64 }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build backend image
    strategy:
      matrix:
        arch: [x64, arm64]
    runs-on: ${{ matrix.arch == 'x64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get UTC ISO8601 timestamp
        run: echo "COMMIT_TIMESTAMP=$(git log -1 --format='%aI' | date -f - --utc '+%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Build and push backend
        uses: docker/build-push-action@v6
        id: build-image
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: self-hosted/docker-build/Dockerfile.backend
          tags: |
            ghcr.io/metricsubs/convex-backend
          cache-from: type=registry,ref=ghcr.io/metricsubs/convex-backend:latest
          cache-to: type=inline
          outputs: push-by-digest=true,type=image,push=true
          provenance: false
          build-args: |
            VERGEN_GIT_SHA=${{ github.sha }}
            VERGEN_GIT_COMMIT_TIMESTAMP=${{ env.COMMIT_TIMESTAMP }}

      - name: Write digest
        uses: cloudposse/github-action-matrix-outputs-write@v1
        id: digest
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: backend-${{ matrix.arch }}
          outputs: |-
            digest: ${{ steps.build-image.outputs.digest }}

  read:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@v1
        id: read
        with:
          matrix-step-name: build
    outputs:
      result: "${{ steps.read.outputs.result }}"
